services:
  streamlit:
    image: aqi-dashboard:latest
    user: root
    tty: true
    command: streamlit run /app/app.py --server.port=8501 --server.address=0.0.0.0
    environment:
      - DB_HOST=
      - DB_PORT=
      - DB_NAME=
      - DB_USER=
      - DB_PASS=
    volumes:
      - ./app:/app
    mem_limit: 1g
    memswap_limit: 2g
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - streamlit
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
